### ISSUE TITLE
CMS::Mailer

### ISSUE THREAD

**Issue by jet-snowman** [knodeit/dolphin-cms#8]
Implement mailer in dolphin-lib

1) Make a fork from dolphin-lib

2) Add KNMailer namespace

3) Create 3 providers:
  a) mandrill  
  b) mailchimp
  c) database

4) Mailer must have factory for providers, each provider must have method getContent(params) and returns already compiled content with replaced variables.

5) During initialization developer must send type of provider and keep object in memory, also this object can reload by user, for example when smtp settings were changed or user set another provider. 

6) Mailer must have at least 2 methods
  a) render('name_of_template', params) - return promise but resolve content
  b) send('name_of_template', params) - return promise and resolve with status is ok, reject if fail 

7) Mailer can have global variables like {{host}} so create method setVariable(name, value)

8) these methods must support sending files

Create a module CMSMailer which must support the following logic:
1) The module must load settings from DB
2) The module must have method getMailer and this method must return configured mailer object from dolphin-lib.

Technical information:
1) need to create base class for provider 
2) Mailer constructor will take the parameters

**Comment by archik745** [comment]
dolphin-lib fork with updates
https://github.com/archik745/dolphin-lib/commit/0245dbfddcccc751a24a3967bf9dc3ec92c960da

dolphin-cms (branch mailer_8) with updates
https://github.com/knodeit/dolphin-cms/commit/57edfc4027721bb833aee6bfc6ef1ce6f9526137
https://github.com/knodeit/dolphin-cms/commit/37a51874c8ecd1773e4fed921705e4d618d674ec

provider examples
emailtemplates from db: https://github.com/archik745/dolphin-lib/wiki/DBProvider
mandrill: https://github.com/archik745/dolphin-lib/wiki/MandrillProvider

**Comment by jet-snowman** [comment]
done
